name: Deploy SOR to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Descargar codigo (Checkout)
        uses: actions/checkout@v4

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configurar NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restaurar paquetes NuGet
        run: nuget restore SOR.sln

      - name: Compilar aplicacion en modo Release
        run: msbuild SOR/SOR.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}\build_package\SOR.zip" /verbosity:minimal

      - name: Desplegar a Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SOR'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}\build_package\SOR.zip'
